DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ROLE VARCHAR(100)
);

INSERT INTO USERS (USER_ID, PASSWORD, ROLE) VALUES ('admin', 'password', 'admin');